= Sakura Ikebana Delivery

:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

// legajos

== Introducción

Sakura Haruno junto a su amiga de la infancia Ino Yamanaka, tienen un negocio de arreglos
florales típicos japoneses (ikebana). Ino se encarga de preparar los arreglos florales, y Sakura
se encarga del delivery de los mismos.

La florería Yamanaka-Haruno está ubicada en una aldea ninja, que suele ser atacada por
ninjas enemigos. Esto complica el trabajo de Sakura que debe entregar los pedidos evitando
y combatiendo a los ninjas enemigos.

El objetivo de este trabajo es desarrollar un videojuego en el cual Sakura entregue
los pedidos sin perder la vida a manos de los ninjas enemigos.

== Descripción

- *Métodos de la clase Sakura*
   
 * `mirarIzquierda()`: La dirección de Sakura se establece en Math.PI.
 
 * `mirarDerecha()`: La dirección de Sakura se establece en 0.

 * `mirarArriba()`: La dirección de Sakura se establece en - Math.PI / 2.
 
 * `mirarAbajo()`: La dirección de Sakura se establece en Math.PI / 2.

 * `dibujar()`: Dibuja a Sakura en el entorno, dependiendo de la dirección en la que se encuentre se va a dibujar de distinta manera.

 * `mover()`: Sakura se mueve en el entorno hacia la dirección elegida.

 * `colisionoConElEntorno()`: Este boolean devuelve true si Sakura choca con los bordes del entorno.

 * `colisionoConNinja()`: Este boolean devuelve true si Sakura choca con un ninja.

 * `llegoACasaDelPedido()`: Este boolean devuelve `true` si Sakura pasa por en frente de la casa donde tiene que llevar el pedido.

 * `salioDeCalle()`: El método verifica si Sakura se intenta mover por
 fuera de las calles, si es así devuelve true. Esta compuesto por dos
 partes, una verifica si sale de las calles verticales, es decir por
 los costados. Y la otra verifica si sale de las calles horizontales,
 es decir por arriba o abajo de las calles. En cada caso, se verifica también que no esté en una intersección entre calles, ya que en ese caso sí podría avanzar y moverse.

 * `noAvanzar()`: Limita el movimiento de Sakura dependiendo de si está saliendo por los bordes del entorno o si está saliendo de las calles.

 * `correr()`: La velocidad de Sakura se establece en 4.

 * `caminar()`: La velocidad de Sakura se establece en 2.

 * `lanzarRasengan()`: Crea y retorna un rasengan que va hacia la última dirección en la que se movió Sakura.

 - *Métodos de la clase Ninja*
   
 * `dibujar()`: Dibuja a un ninja en el entorno, dependiendo de la dirección en la que se encuentre se va a dibujar de distinta manera.

 * `mover()`: El ninja se mueve en el entorno siempre en la misma dirección. Si choca contra los bordes del entorno, reaparece del lado contrario.

 * `getDireccion()`: Se utiliza en la clase Juego, para la reaparición de los ninjas.

 * `getX()`: Se utiliza en los métodos `colisionoConNinja` en la clase Sakura y en la clase Rasengan.

 * `getY()`: Se utiliza en los métodos `colisionoConNinja` en la clase Sakura y en la clase Rasengan.

 - *Métodos de la clase Casa*
   
 * `dibujar()`: Dibuja una casa roja o una casa azul en el entorno, dependiendo de su número.

 * `marcar()`: Dibuja una flecha encima de la casa elegida. En las casas que están en el borde superior de la pantalla la flecha que marca la casa se dibuja desde abajo para que no salga de la pantalla.

 * `getX()`: Se utiliza en el método `llegoACasaDelPedido` en la clase Sakura.

 * `getY()`: Se utiliza en el método `llegoACasaDelPedido` en la clase Sakura.

 - *Método de la clase Calle*
   
 * `dibujar()`: Dibuja un rectángulo en el entorno, representando una calle.

 - *Métodos de la clase Rasengan*
   
 * `dibujar()`: Dibuja el rasengan en el entorno.

 * `mover()`: El rasengan se mueve en el entorno hacia la dirección elegida.

 * `colisionoConElEntorno()`: Este boolean devuelve true si el rasengan choca con los bordes del entorno.
 
 * `colisionoConLaCiudad()`: Este boolean devuelve true si el rasengan se sale de las calles.
 
 * `colisionoConNinja()`: Este boolean devuelve true si el rasengan choca con un ninja.

== Implementación

*Clase Sakura*

```java
		
public class Sakura {

	private double x;
	private double y;
	private double velocidad;
	private double tamaño;
	private double ancho;
	private double direccion;
	private Image sakuraMirandoHaciaFrente;
	private Image sakuraMirandoHaciaDerecha;
	private Image sakuraMirandoHaciaIzquierda;

	public Sakura(double x, double y, double direccion) {
		this.x = x;
		this.y = y;
		this.sakuraMirandoHaciaFrente = Herramientas.cargarImagen("sakuraMirandoHaciaFrente.png");
		this.sakuraMirandoHaciaDerecha = Herramientas.cargarImagen("sakuraMirandoHaciaDerecha.png");
		this.sakuraMirandoHaciaIzquierda = Herramientas.cargarImagen("sakuraMirandoHaciaIzquierda.png");
		this.tamaño = sakuraMirandoHaciaFrente.getHeight(null);
		this.ancho = sakuraMirandoHaciaFrente.getWidth(null);
	}

	public void mirarIzquierda() {
		direccion = Math.PI;
	}
	
	public void mirarDerecha() {
		direccion = 0;
	}
	
	public void mirarArriba() {
		direccion = - Math.PI / 2;
	}

	public void mirarAbajo() {
		direccion = Math.PI / 2;
	}
	
	public void dibujar(Entorno e) {
		if (direccion == Math.PI) {
			e.dibujarImagen(sakuraMirandoHaciaIzquierda, x, y, 0);
		} else {
			if (direccion == 0) {
				e.dibujarImagen(sakuraMirandoHaciaDerecha, x, y, 0);
			} else {
				e.dibujarImagen(sakuraMirandoHaciaFrente, x, y, 0);
			}
		}
	}
	
	public void mover(Entorno e) {
		x += velocidad * Math.cos(direccion);
		y += velocidad * Math.sin(direccion);
	}

	public boolean colisionoConElEntorno(Entorno e) {
		return x < tamaño / 2 || x > e.ancho() - tamaño / 2 || y < tamaño / 2 || y > e.alto() - tamaño / 2;
	}

	public boolean colisionoConNinja(Entorno e, Ninja n) {
		if (n == null) {
			return false;
		}
		return x > n.getX() - tamaño / 2 && x < n.getX() + tamaño / 2 && y > n.getY() - tamaño / 2
				&& y < n.getY() + tamaño / 2;
	}

	public boolean llegoACasaDelPedido(Casa c) {
		return (Math.abs(x - c.getX()) < 55 && Math.abs(y - c.getY()) < 50);
	}

	public boolean salioDeCalle(Entorno e) {
		boolean noAvanza = false;
		// verificaciones en calles horizontales
		if (((y + tamaño < e.alto() / 2 + 45 && y + tamaño > e.alto() / 2 - 1) // calle del medio (parte de arriba)
				|| (y + tamaño >= e.alto() / 2 + 45 && y + tamaño < e.alto() / 2 + 50) // calle del medio (parte de abajo)
				|| (y + tamaño < e.alto() / 5 + 45 && y + tamaño > e.alto() / 5 - 1) // calle de arriba (parte de arriba)
				|| (y + tamaño >= e.alto() / 5 + 45 && y + tamaño < e.alto() / 5 + 50) // calle de arriba (parte de abajo)
				|| (y + tamaño < e.alto() - e.alto() / 5 + 45 && y + tamaño > e.alto() - e.alto() / 5 - 1) // calle de abajo (parte de arriba)
				|| (y + tamaño >= e.alto() - e.alto() / 5 + 45 && y + tamaño < e.alto() - e.alto() / 5 + 50))) { // calle de abajo (parte de abajo)

			if (((x + ancho / 2 < e.ancho() / 8)
					|| (x + ancho / 2 > e.ancho() / 8 + 40 && x + ancho / 2 < e.ancho() / 2.66)
					|| (x + ancho / 2 > e.ancho() / 2.66 + 40 && x + ancho / 2 < e.ancho() - e.ancho() / 2.66)
					|| (x + ancho / 2 > e.ancho() - e.ancho() / 2.66 + 40 && x + ancho / 2 < e.ancho() - e.ancho() / 8)
					|| (x + ancho / 2 > e.ancho() - e.ancho() / 8 + 40))) {
				noAvanza = true;
			}
		// verificaciones en calles verticales	
		} else if ((x - ancho / 3 < e.ancho() / 8 - 20 && x - ancho / 3 > e.ancho() / 8 - 40) // Primera calle desde la izquierda (parte izquierda)
				|| (x + ancho / 3 > e.ancho() / 8 + 20 && x + ancho / 3 < e.ancho() / 8 + 40) // Primera calle desde la izquierda (parte derecha)
				|| (x - ancho / 3 < e.ancho() / 2.66 - 20 && x - ancho / 3 > e.ancho() / 2.66 - 40) // segunda calle (parte izquierda)
				|| (x + ancho / 3 > e.ancho() / 2.66 + 20 && x + ancho / 3 < e.ancho() / 2.66 + 40) // segunda calle (parte derecha)
				|| (x - ancho / 3 < e.ancho() - e.ancho() / 2.66 - 20
							&& x - ancho / 3 > e.ancho() - e.ancho() / 2.66 - 40)	// tercera calle (parte izquierda)
				|| (x + ancho / 3 > e.ancho() - e.ancho() / 2.66 + 20				
						&& x + ancho / 3 < e.ancho() - e.ancho() / 2.66 + 40)		// tercera calle (parte derecha)
				|| (x - ancho / 3 < e.ancho() - e.ancho() / 8 - 20 && x - ancho / 3 > e.ancho() - e.ancho() / 8 - 40) // cuarta calle (parte izquierda)
				|| (x + ancho / 3 > e.ancho() - e.ancho() / 8 + 20 && x + ancho / 3 < e.ancho() - e.ancho() / 8 + 40)) { // cuarta calle (parte derecha)

			if ((y + tamaño / 2 < e.alto() / 5 - 20)
					|| (y + tamaño / 2 > e.alto() / 5 + 20 && y + tamaño / 2 < e.alto() / 2 - 20)
					|| (y + tamaño / 2 > e.alto() / 2 + 20 && y + tamaño / 2 < e.alto() - e.alto() / 5 - 20)
					|| (y + tamaño / 2 > e.alto() - e.alto() / 5 + 20)) {
				noAvanza = true;
			}
		} else {
			noAvanza = false;
		}
		return noAvanza;
	}

	public void noAvanzar(Entorno e) {
		if (x < tamaño / 2) {
			x += velocidad;
		}
		if (y < tamaño / 2) {
			y += velocidad;
		}
		if (x > e.ancho() - tamaño / 2) {
			x -= velocidad;
		}
		if (y > e.alto() - tamaño / 2) {
			y -= velocidad;
		}

		// condiciones para que no salga de las calles
		if (((y + tamaño < e.alto() / 2 + 45 && y + tamaño > e.alto() / 2 - 1)
				|| (y + tamaño < e.alto() / 5 + 45 && y + tamaño > e.alto() / 5 - 1)
				|| (y + tamaño < e.alto() - e.alto() / 5 + 45 && y + tamaño > e.alto() - e.alto() / 5 - 1))) {
			y += velocidad;
		}

		if ((y + tamaño >= e.alto() / 2 + 45 && y + tamaño < e.alto() / 2 + 50
				|| (y + tamaño >= e.alto() / 5 + 45 && y + tamaño < e.alto() / 5 + 50)
				|| (y + tamaño >= e.alto() - e.alto() / 5 + 45 && y + tamaño < e.alto() - e.alto() / 5 + 50))) {
			y -= velocidad;

		} else if ((x - ancho / 3 < e.ancho() / 8 - 20 && x - ancho / 3 > e.ancho() / 8 - 40)
				|| (x - ancho / 3 < e.ancho() / 2.66 - 20 && x - ancho / 3 > e.ancho() / 2.66 - 40)
				|| (x - ancho / 3 < e.ancho() - e.ancho() / 2.66 - 20
						&& x - ancho / 3 > e.ancho() - e.ancho() / 2.66 - 40)
				|| (x - ancho / 3 < e.ancho() - e.ancho() / 8 - 20 && x - ancho / 3 > e.ancho() - e.ancho() / 8 - 40)) {
			x += velocidad;
		}

		else if ((x + ancho / 3 > e.ancho() / 8 + 20 && x + ancho / 3 < e.ancho() / 8 + 40)
				|| (x + ancho / 3 > e.ancho() / 2.66 + 20 && x + ancho / 3 < e.ancho() / 2.66 + 40)
				|| (x + ancho / 3 > e.ancho() - e.ancho() / 2.66 + 20
						&& x + ancho / 3 < e.ancho() - e.ancho() / 2.66 + 40)
				|| (x + ancho / 3 > e.ancho() - e.ancho() / 8 + 20 && x + ancho / 3 < e.ancho() - e.ancho() / 8 + 40)) {
			x -= velocidad;
		}
	}

	public void correr(Entorno e) {
		velocidad = 4;
	}

	public void caminar(Entorno e) {
		velocidad = 2;
	}

	public Rasengan lanzarRasengan(Entorno e) {
		Rasengan rasengan = new Rasengan(e, x, y, direccion);
		return rasengan;
	}
}
		
```



*Clase Ninja*
```java
public class Ninja {

	private double x;
	private double y;
	private double velocidad;
	private double direccion;
	private double tamaño;
	private Image ninjaMirandoHaciaDerecha;
	private Image ninjaMirandoHaciaIzquierda;

	public Ninja(double x, double y, double direccion) {
		this.x = x;
		this.y = y;
		this.velocidad = 1.5;
		this.direccion = direccion;
		this.ninjaMirandoHaciaDerecha = Herramientas.cargarImagen("ninjaMirandoHaciaDerecha.png");
		this.ninjaMirandoHaciaIzquierda = Herramientas.cargarImagen("ninjaMirandoHaciaIzquierda.png");
		this.tamaño = ninjaMirandoHaciaDerecha.getHeight(null);
	}

	public void dibujar(Entorno e) {
		if (direccion == Math.PI) {
			e.dibujarImagen(ninjaMirandoHaciaIzquierda, x, y, 0);
		} else {
			e.dibujarImagen(ninjaMirandoHaciaDerecha, x, y, 0);
		}
	}

	public void mover(Entorno e) {
		x += velocidad * Math.cos(direccion);
		y += velocidad * Math.sin(direccion);
		if (x < tamaño / 2) {
			x += e.ancho();
		}
		if (y < tamaño / 2) {
			y += e.alto();
		}
		if (x > e.ancho() - tamaño / 2) {
			x -= e.ancho();
		}
		if (y > e.alto() - tamaño / 2) {
			y -= e.alto();
		}
	}

	public double getDireccion() {
		return direccion;
	}

	public double getX() {
		return x;
	}

	public double getY() {
		return y;
	}
}
```

*Clase Casa*
```java
public class Casa {

	private int numero;
	private double x;
	private double y;
	private double tamaño;
	private double direccion;
	private Image casaRoja;
	private Image casaAzul;
	private Image flecha;

	public Casa(int numero, double x, double y, double direccion) {
		this.numero = numero;
		this.direccion = direccion;
		this.x = x;
		this.y = y;
		this.flecha = Herramientas.cargarImagen("flecha.gif");
		this.casaRoja = Herramientas.cargarImagen("casaRoja.png");
		this.casaAzul = Herramientas.cargarImagen("casaAzul.png");
		this.tamaño = casaRoja.getWidth(null);
	}

	public void dibujar(Entorno e) {
		if (this.numero % 2 == 0) {
			e.dibujarImagen(casaRoja, x, y, direccion, 0.8);
		} else {
			e.dibujarImagen(casaAzul, x, y, direccion, 0.8);
		}
	}

	public void marcar(Entorno e) {
		if (this.numero == 9 || this.numero == 13 || this.numero == 17 || this.numero == 21 || this.numero == 25
				|| this.numero == 29 || this.numero == 33 || this.numero == 37) {
			e.dibujarImagen(flecha, x, y + tamaño, -Math.PI / 2, 1.5);
		} else {
			e.dibujarImagen(flecha, x, y - tamaño, Math.PI / 2, 1.5);
		}
	}

	public double getX() {
		return x;
	}

	public double getY() {
		return y;
	}

}
```

*Clase Calle*

```java
public class Calle {

	private double x;
	private double y;
	private int ancho;
	private int alto;
	private Color color;

	public Calle(double x, double y, int ancho, int alto) {
		this.x = x;
		this.y = y;
		this.ancho = ancho;
		this.alto = alto;
		this.color = Color.GRAY;
	}

	public void dibujar(Entorno e) {
		e.dibujarRectangulo(x, y, ancho, alto, 0, color);
	}
}
```

*Clase Rasengan*

```java
public class Rasengan {

	private double x;
	private double y;
	private double tamaño;
	private double velocidad;
	private Image rasengan;
	private double direccion;
	private double ancho;

	public Rasengan(Entorno e, double x, double y, double direccion) {
		this.x = x;
		this.y = y;
		this.velocidad = 5;
		this.direccion = direccion;
		this.rasengan = Herramientas.cargarImagen("Rasengan.png");
		this.tamaño = rasengan.getHeight(null);
		this.ancho = rasengan.getWidth(null);
	}

	public void dibujar(Entorno e) {
		e.dibujarImagen(rasengan, x , y , 0);
	}

	public void mover() {
		x += velocidad * Math.cos(direccion);
		y += velocidad * Math.sin(direccion);
	}

	public boolean colisionoConElEntorno(Entorno e) {
		return x < tamaño / 2 || x > e.ancho() - tamaño / 2 || y < tamaño / 2 || y > e.alto() - tamaño / 2;
	}

	public boolean colisionoConLaCiudad(Entorno e) {
		boolean colisiono = false;
		// verificaciones en calles horizontales
		if (((y + tamaño < e.alto() / 2 + 5 && y + tamaño > e.alto() / 2 - 110) // calle del medio (parte de arriba)
				|| (y + tamaño >= e.alto() / 2 + 5 && y + tamaño < e.alto() / 2 + 20) // calle de medio (parte de abajo)
				|| (y + tamaño < e.alto() / 5 + 5 && y + tamaño > e.alto() / 5 - 110) // calle de arriba (parte de arriba)
				|| (y + tamaño >= e.alto() / 5 + 5 && y + tamaño < e.alto() / 5 + 20) // calle de arriba (parte de abajo)
				|| (y + tamaño < e.alto() - e.alto() / 5 + 5 && y + tamaño > e.alto() - e.alto() / 5 - 110) // calle de abajo (parte de arriba)
				|| (y + tamaño >= e.alto() - e.alto() / 5 + 50))){ // calle de abajo (parte de abajo)

			if (((x + ancho / 2 < e.ancho() / 8)
					|| (x + ancho / 2 > e.ancho() / 8 + 60 && x + ancho / 2 < e.ancho() / 2.66)
					|| (x + ancho / 2 > e.ancho() / 2.66 + 60 && x + ancho / 2 < e.ancho() - e.ancho() / 2.66)
					|| (x + ancho / 2 > e.ancho() - e.ancho() / 2.66 + 60 && x + ancho / 2 < e.ancho() - e.ancho() / 8)
					|| (x + ancho / 2 > e.ancho() - e.ancho() / 8 + 60))) {
				colisiono = true;
			}
		// verificaciones en calles verticales
		} else if ((x - ancho / 3 < e.ancho() / 8 - 20 && x - ancho / 3 > e.ancho() / 8 - 40) // Primera calle desde izquierda (parte izquierda)
				|| (x + ancho / 3 > e.ancho() / 8 + 20 && x + ancho / 3 < e.ancho() / 8 + 40) // Primera calle desde izquierda (parte derecha)
				|| (x - ancho / 3 < e.ancho() / 2.66 - 20 && x - ancho / 3 > e.ancho() / 2.66 - 40) // segunda calle (parte izquierda)
				|| (x + ancho / 3 > e.ancho() / 2.66 + 20 && x + ancho / 3 < e.ancho() / 2.66 + 40) // segunda calle (parte derecha)
				|| (x - ancho / 3 < e.ancho() - e.ancho() / 2.66 - 20
						&& x - ancho / 3 > e.ancho() - e.ancho() / 2.66 - 40)	// tercera calle (parte izquierda)
				|| (x + ancho / 3 > e.ancho() - e.ancho() / 2.66 + 20
						&& x + ancho / 3 < e.ancho() - e.ancho() / 2.66 + 40)  // tercera calle (parte derecha)
				|| (x - ancho / 3 < e.ancho() - e.ancho() / 8 - 20 && x - ancho / 3 > e.ancho() - e.ancho() / 8 - 40) // cuarta calle (parte izquierda)
				|| (x + ancho / 3 > e.ancho() - e.ancho() / 8 + 20 && x + ancho / 3 < e.ancho() - e.ancho() / 8 + 40)) { // cuarta calle (parte derecha)
		} else {
			colisiono = false;
		}
		return colisiono;
	}

	public boolean colisionoConNinja(Ninja n) {
		return Math.abs(x - n.getX()) < 20 && Math.abs(y - n.getY()) < 20;
	}
}
```

*Clase Juego*

```java
public class Juego extends InterfaceJuego {

	// El objeto Entorno que controla el tiempo y otros
	private Entorno entorno;
	private Calle[] calles;
	private Casa[] casas;
	private Sakura sakura;
	private Ninja[] ninjas;
	private Rasengan rasengan;
	private Casa casaDelPedido;
	private int numeroCasaDelPedido;
	private Random numeroRandom;
	private int puntos;
	private int ninjasEliminados;
	private Image fondo;
	private Image lineasCalle;
	private Image arboles;
	private Image imagenGameOver;
	private int cantidadDeRasengans;
	private double[][] ninjasReapariciones;
	private int ninjaQueReaparecera;
	private boolean finDelJuego;
	public Juego() {

		// Inicializa el objeto entorno
		this.entorno = new Entorno(this, "Sakura Ikebana Delivery", 800, 600);
		sakura = new Sakura(entorno.ancho() / 2, entorno.alto() / 2, -Math.PI / 2);
		ninjas = new Ninja[6];
		ninjasReapariciones = new double[3][3];
		puntos = 0;
		ninjasEliminados = 0;
		cantidadDeRasengans = 3;
		ninjaQueReaparecera = 0;
		int i = 0;
		double x = entorno.ancho() / 8;
		double y = entorno.alto() / 2;
		double ang = Math.PI / 2;
		finDelJuego = false;
		// Creacion de ninjas
		for (int j = 0; j < ninjas.length; j++) {
			ninjas[i++] = new Ninja(x, y, ang);

			if (i == 4) {
				x = entorno.ancho() / 2;
				y = entorno.alto() / 5.2;
				ang = 0;
			}
			if (i == 5) {
				x = entorno.ancho() / 2;
				y = entorno.alto() - y - entorno.alto() / (entorno.alto() / 10);
				ang = 0;
			} else {
				x += 200;
				ang = ang * -1;
			}
		}

		// Creacion de calles y casas
		calles = new Calle[7];
		int k = 0;
		double xx = entorno.ancho() / 2;
		int yy = entorno.alto() / 5;
		int ancho = entorno.ancho();
		int alto = 40;
		casas = new Casa[41];
		int xCasa = 200;
		int yCasa = 40;
		int g = 0;
		for (int j = 0; j < calles.length; j++) {
			calles[k++] = new Calle(xx, yy, ancho, alto);

			if (k == 1) {
				yy = entorno.alto() / 2;
				for (int c = 0; c < 3; c++) {
					casas[g++] = new Casa(c, xCasa, yy - 230, Math.PI);
					xCasa += 200;
				}
				xCasa = 200;
				for (int d = 3; d < 6; d++) {
					casas[g++] = new Casa(d, xCasa, yy - 50, Math.PI);
					xCasa += 200;
				}
				xCasa = 200;
				for (int e = 6; e < 9; e++) {
					casas[g++] = new Casa(e, xCasa, yy + 130, Math.PI);
					xCasa += 200;
				}

			}
			if (k == 2) {
				yy = entorno.alto() - entorno.alto() / 5;
			}
			if (k == 3 || k == 4 || k == 5 || k == 6) {

				yy = entorno.alto() / 2;
				ancho = 40;
				alto = entorno.alto();

				if (k == 3) {
					xx = entorno.ancho() / 8;
					for (int f = 9; f < 13; f++) {
						casas[g++] = new Casa(f, xx - 50, yCasa, Math.PI / 2);
						yCasa += 170;
					}
					yCasa = 40;
					for (int h = 13; h < 17; h++) {
						casas[g++] = new Casa(h, xx + 50, yCasa, Math.PI / 2);
						yCasa += 170;
					}
					yCasa = 40;

				}
				if (k == 4) {
					xx = entorno.ancho() / 2.66;
					for (int l = 17; l < 21; l++) {
						casas[g++] = new Casa(l, xx - 50, yCasa, Math.PI / 2);
						yCasa += 165;
					}
					yCasa = 40;
					for (int m = 21; m < 25; m++) {
						casas[g++] = new Casa(m, xx + 50, yCasa, Math.PI / 2);
						yCasa += 165;
					}
					yCasa = 40;
				}
				if (k == 5) {
					xx = entorno.ancho() - entorno.ancho() / 2.66;
					for (int l = 25; l < 29; l++) {
						casas[g++] = new Casa(l, xx - 50, yCasa, Math.PI / 2);
						yCasa += 165;
					}
					yCasa = 40;
					for (int m = 29; m < 33; m++) {
						casas[g++] = new Casa(m, xx + 50, yCasa, Math.PI / 2);
						yCasa += 165;
					}
					yCasa = 40;
				}
				if (k == 6) {
					xx = entorno.ancho() - entorno.ancho() / 8;
					for (int q = 33; q < 37; q++) {
						casas[g++] = new Casa(q, xx - 50, yCasa, Math.PI / 2);
						yCasa += 165;
					}
					yCasa = 40;
					for (int w = 37; w < 41; w++) {
						casas[g++] = new Casa(w, xx + 50, yCasa, Math.PI / 2);
						yCasa += 165;
					}
				}
			}
			fondo = Herramientas.cargarImagen("fondo.png");
			lineasCalle = Herramientas.cargarImagen("lineasCalle.png");
			arboles = Herramientas.cargarImagen("arboles.png");
		}
		numeroRandom = new Random();
		numeroCasaDelPedido = numeroRandom.nextInt(casas.length);
		casaDelPedido = casas[numeroCasaDelPedido];
		imagenGameOver = Herramientas.cargarImagen("gameover.png");

		// Inicializar lo que haga falta para el juego
		// ...

		// Inicia el juego!
		this.entorno.iniciar();
	}

	/**
	 * Durante el juego, el método tick() será ejecutado en cada instante y por lo
	 * tanto es el método más importante de esta clase. Aquí se debe actualizar el
	 * estado interno del juego para simular el paso del tiempo (ver el enunciado
	 * del TP para mayor detalle).
	 */

	public void tick() {
		entorno.dibujarImagen(fondo, entorno.ancho() / 2, entorno.alto() / 2, 0);

		for (Calle c : calles) {
			c.dibujar(entorno);
		}

		entorno.dibujarImagen(lineasCalle, entorno.ancho() / 2, entorno.alto() / 2, 0);

		for (Ninja n : ninjas) {
			if (n != null) {
				n.dibujar(entorno);
				n.mover(entorno);
				if (sakura.colisionoConNinja(entorno, n)) {
					finDelJuego = true;
				}
			}
		}

		for (Casa c : casas) {
			if (c != null) {
				c.dibujar(entorno);
			}
		}

		sakura.dibujar(entorno);

		if (sakura.colisionoConElEntorno(entorno) || sakura.salioDeCalle(entorno)) {
			sakura.noAvanzar(entorno);
		}

		if (entorno.estaPresionada('a') || entorno.estaPresionada('d') || entorno.estaPresionada('w') || entorno.estaPresionada('s')) {
			sakura.mover(entorno);
		}

		if (entorno.estaPresionada('a')) {
			sakura.mirarIzquierda();
		} else {
			if (entorno.estaPresionada('d')) {
				sakura.mirarDerecha();
			} else {
				if (entorno.estaPresionada('w')) {
					sakura.mirarArriba();
				} else {
					if (entorno.estaPresionada('s')) {
						sakura.mirarAbajo();
					}
				}
			}
		}

		if (rasengan != null) {
			rasengan.dibujar(entorno);
			rasengan.mover();

			for (int i = 0; i < ninjas.length; i++) {
				if (rasengan != null && ninjas[i] != null && rasengan.colisionoConNinja(ninjas[i])) {
					Herramientas.cargarSonido("ninjaDie.wav").start();
					ninjasReapariciones[ninjaQueReaparecera][0] = ninjas[i].getX();
					ninjasReapariciones[ninjaQueReaparecera][1] = ninjas[i].getY();
					ninjasReapariciones[ninjaQueReaparecera][2] = ninjas[i].getDireccion();
					ninjas[i] = null;
					rasengan = null;
					ninjasEliminados++;
					ninjaQueReaparecera += 1;
				}
			}
			if (rasengan != null
					&& (rasengan.colisionoConLaCiudad(entorno) || rasengan.colisionoConElEntorno(entorno))) {
				rasengan = null;
			}
		}
		if (rasengan == null && cantidadDeRasengans != 0) {

			if (entorno.sePresiono(entorno.TECLA_ESPACIO)) {
				rasengan = sakura.lanzarRasengan(entorno);
				cantidadDeRasengans -= 1;
			}
		}
		if (sakura.llegoACasaDelPedido(casaDelPedido)) {
			numeroCasaDelPedido = numeroRandom.nextInt(casas.length);
			casaDelPedido = casas[numeroCasaDelPedido];
			puntos += 5;
			cantidadDeRasengans = 3;
			ninjaQueReaparecera = 0;
			for (int i = 0; i < ninjas.length; i++) {
				if (ninjas[i] == null && !(ninjasReapariciones[ninjaQueReaparecera][0]<0)) {
					ninjas[i] = new Ninja(ninjasReapariciones[ninjaQueReaparecera][0], ninjasReapariciones[ninjaQueReaparecera][1], ninjasReapariciones[ninjaQueReaparecera][2]);
					ninjasReapariciones[ninjaQueReaparecera][0] = -10;
					ninjaQueReaparecera += 1;
				}
			}
			if (ninjaQueReaparecera > 0) {
				Herramientas.cargarSonido("goNinja.wav").start();
			}
			ninjaQueReaparecera = 0;
			
		}
		if (entorno.estaPresionada(entorno.TECLA_SHIFT)) {
			sakura.correr(entorno);
		} else {
			sakura.caminar(entorno);
		}

		entorno.dibujarImagen(arboles, entorno.ancho() / 2, entorno.alto() / 2, 0);
		casaDelPedido.marcar(entorno);
		entorno.cambiarFont("sans", entorno.alto() / 33, Color.RED);
		entorno.escribirTexto("Rasengans: " + cantidadDeRasengans, entorno.ancho() / 78, entorno.alto() / 15);
		entorno.escribirTexto("Pts: " + puntos, entorno.ancho() - entorno.ancho() / 11, entorno.alto() / 35);
		entorno.escribirTexto("Kills: " + ninjasEliminados, entorno.ancho() / 80, entorno.alto() / 35);

		if (finDelJuego) {
			entorno.dibujarImagen(imagenGameOver, entorno.ancho() / 2, entorno.alto() / 2, 0);
			entorno.cambiarFont("sans", entorno.alto() / 33, Color.CYAN);
			entorno.escribirTexto("Puntuacion Total: " + puntos, entorno.ancho() / 2.5, entorno.alto() - 90);
		}

		// Procesamiento de un instante de tiempo
		// ...
	}

	@SuppressWarnings("unused")
	public static void main(String[] args) {
		Juego juego = new Juego();
	}
}
```

